[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["tokio", "image", "debug"] }
iced_native = "0.10"
iced_winit = "0.10"
iced_graphics = "0.10"
iced_style = "0.10"
iced_widget = "0.12"
iced_futures = "0.12"
log = "0.4"
